permalink: /:year:month:day/:title
url: #nikorekhviashvili.github.io
baseurl: /windows-95
newbaseurl: /windows-95



# variables
name: Nikos Portfolio
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
